# Generated by Django 6.0.5 on 2026-06-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
