# Generated by Django 6.0.5 on 2026-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_custom_user_options_custom_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='blog/user/avatar'),
        ),
    ]
