# Generated by Django 6.0.5 on 2026-06-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prose', '0002_alter_document_id'),
        ('user_auth', '0003_alter_custom_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='bio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prose.document'),
        ),
    ]
