# Generated by Django 6.0.5 on 2026-06-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prose', '0002_alter_document_id'),
        ('user_auth', '0004_custom_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='Skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='Social_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prose.document'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Undefined')], default='u', max_length=1),
        ),
    ]
