# Generated by Django 6.0.5 on 2026-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_custom_user_skills_custom_user_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='email_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
