# Generated by Django 6.0.5 on 2026-06-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.DO_NOTHING, to='blogpost.category'),
        ),
    ]
