# Generated by Django 6.0.5 on 2026-06-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Thumbnail',
            new_name='thumbnail',
        ),
    ]
