# Generated by Django 6.0.5 on 2026-06-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_rename_content_post_body_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Thumbnail',
            new_name='thumbnail',
        ),
    ]
