# Generated by Django 6.0.5 on 2026-06-03 17:39

import prose.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_rename_body_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mc',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pr',
            field=prose.fields.RichTextField(null=True),
        ),
    ]
