# Generated by Django 6.0.5 on 2026-06-03 17:40

import prose.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_post_mc_post_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pr',
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
    ]
