# Generated by Django 6.0.5 on 2026-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_remove_post_user_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='ss',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
    ]
