# Generated by Django 6.0.5 on 2026-06-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0008_postcontent_ss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcontent',
            options={'verbose_name': 'Post Content', 'verbose_name_plural': 'Post Contents'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='ss',
        ),
    ]
