# Generated by Django 6.0.5 on 2026-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0009_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
