# Generated by Django 6.0.5 on 2026-06-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0010_postcontent_name'),
        ('prose', '0002_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prose.document'),
        ),
        migrations.DeleteModel(
            name='PostContent',
        ),
    ]
