# Generated by Django 6.0.5 on 2026-06-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0011_alter_post_content_delete_postcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
