# Generated by Django 6.0.5 on 2026-06-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0012_rename_user_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visiblity',
            new_name='visibility',
        ),
    ]
